### ISSUE TITLE
Max number of Input file names

### ISSUE THREAD

**Issue by leohinojosa** [jmezach/MSBuild.Sdk.SqlProj#10]
Hi!
trying to implement the solution ( over 2k sql table and sprocs)  to our sql project, I got the following message 

```
Option 'Argument: table.sql' expects no more than 255 arguments, but 463 were provided.
```
Looking at the code I couldn't find a way to increase this limit, but it seems that it's probably defined in the dotnet `commandline` dependency .

Do you know if there is an easy way to change this limit?

**Comment by jmezach** [comment]
Hi @leohinojosa. First of all, thanks for giving it a try. To be honest I wasn't expecting this. I'll have to dig into this a little bit. It could be related to dotnet/command-line-api#863, which looks to be fixed. Maybe I'll just need to update the dependency.

**Comment by leohinojosa** [comment]
Ah it seems they merged it a couple of weeks ago,
I'll monitor the next release of command-line-api and send you a PR with the change
Thank you @jmezach

**Comment by jmezach** [comment]
Looks like a new version of System.CommandLine has been released which should include the necessary fix for this. I've just pushed some changes for #9 which includes the update. Could you give this [beta package](https://www.nuget.org/packages/MSBuild.Sdk.SqlProj/1.1.0-beta.9) a try to see if that fixes your issue?

**Comment by jmezach** [comment]
Hi @leohinojosa, just a heads-up that [1.1.0](https://www.nuget.org/packages/MSBuild.Sdk.SqlProj/1.1.0) is out now on NuGet which should include the fix for this issue. I'll go ahead and close this now, but don't hesitate to re-open if it still doesn't work for you.

**Comment by leohinojosa** [comment]
Will do! Thanks for the heads up!

**Comment by leohinojosa** [comment]
New version works correctly, 
however in my legacy project we have over 5k sql files, and in macos, we hit a limit on the max number of arguments passed to an executable.
I'll try to figure out a way to split this or to change the ulimits at the os level

Thank you !
