### ISSUE TITLE
Append newline + GO to post and pre deploy scripts

### ISSUE THREAD

**Issue by ErikEJ** [jmezach/MSBuild.Sdk.SqlProj#18]
I am folder comparing with WinMerge the same project built by VS and this.

**Comment by jmezach** [comment]
Yeah, I think this also has to do with the whole merging of scripts that happens in VS. I'm curious though as to what you are comparing exactly. I think there's some additional transformation happing at deployment too.

**Comment by ErikEJ** [comment]
I am comparing the contents of two dacpacs, one built from my original .csproj, and on biult by this SDK project.

I will make sure we add the newline + GO + newline to each script.
