### ISSUE TITLE
postdeploy script appears to be loaded as SQL object script

### ISSUE THREAD

**Issue by ErikEJ** [jmezach/MSBuild.Sdk.SqlProj#19]

**Comment by ErikEJ** [comment]
This happens when building from VS solution, where .csproj and .sqlproj resides in same folder, so probably a non-issue. Does not occur in a command line build

**Comment by jmezach** [comment]
Could you elaborate on what you mean exactly? Do you get an error or something?

**Comment by ErikEJ** [comment]
See above 😄

**Comment by ErikEJ** [comment]
I mean objects defined I my post-deployment script appear as objects in model.xml, and this should not happen.

**Comment by jmezach** [comment]
That's weird. I wonder how having the .sqlproj and the .csproj in the same folder would have any bearing on that behaviour. We do have some default excludes for files in the Pre-Deployment and Post-Deployment folders, perhaps those aren't entirely correct for your case?

**Comment by ErikEJ** [comment]
I probably should not be doing that, it causes other types of issues.
