### ISSUE TITLE
Support linked files

### ISSUE THREAD

**Issue by ErikEJ** [jmezach/MSBuild.Sdk.SqlProj#5]
Following project build a dacpac, but with not tables in model.xml:

```
<Project Sdk="MSBuild.Sdk.SqlProj/1.0.0">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RecoveryMode>Simple</RecoveryMode>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\Database1\Database1\Table1.sql" Link="Table1.sql" />
  </ItemGroup>
</Project>

```
In addition, Publish fails:

```
1>------ Build started: Project: ConsoleApp1, Configuration: Release Any CPU ------
1>Using package name ConsoleApp1 and version 1.0.0
1>Setting property RecoveryMode to value Simple
1>Using SQL Server version Sql150
1>Writing model to C:\Users\Erik\Source\Repos\ConsoleApp7\ConsoleApp1\obj\Release\netstandard2.0\ConsoleApp1.dacpac
1>ConsoleApp1 -> C:\Users\Erik\Source\Repos\ConsoleApp7\ConsoleApp1\bin\Release\netstandard2.0\ConsoleApp1.dacpac
2>------ Publish started: Project: ConsoleApp1, Configuration: Release Any CPU ------
2>dotnet C:\Users\Erik\.nuget\packages\msbuild.sdk.sqlproj\1.0.0\Sdk\../tools/netcoreapp3.1/BuildDacpac.dll -o "obj\Release\netstandard2.0\ConsoleApp1.dacpac" -n ConsoleApp1 -v 1.0.0 -sv Sql150   -p RecoveryMode=Simple
2>Using package name ConsoleApp1 and version 1.0.0
2>Setting property RecoveryMode to value Simple
2>Using SQL Server version Sql150
2>Deleting existing file C:\Users\Erik\Source\Repos\ConsoleApp7\ConsoleApp1\obj\Release\netstandard2.0\ConsoleApp1.dacpac
2>Writing model to C:\Users\Erik\Source\Repos\ConsoleApp7\ConsoleApp1\obj\Release\netstandard2.0\ConsoleApp1.dacpac
2>ConsoleApp1 -> C:\Users\Erik\Source\Repos\ConsoleApp7\ConsoleApp1\bin\Release\netstandard2.0\ConsoleApp1.dacpac
2>Manifest file not found at 'C:\Users\Erik\Source\Repos\ConsoleApp7\ConsoleApp1\ConsoleApp1.nuspec'
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

```

**Comment by jmezach** [comment]
@ErikEJ Looking at your project file I'm not surprised that the table doesn't end up in the resulting `.dacpac` because the build action for `Table1.sql` is set to `None`. Could you try changing that to `Content` and see if that works?

As for the publish, I'm not entirely sure what `dotnet publish` should do in this case. Perhaps `dotnet pack` would be more appropriate. Looking at the error though it seems that the publish actually does a pack, since it seems to be looking for a `.nuspec` file. Have you added a `.nuspec` file to the project as described [here](https://github.com/jmezach/MSBuild.Sdk.SqlProj#packaging-support).

**Comment by ErikEJ** [comment]
Of course! Adding as Content works like a charm - and "Build" works just as expected.

**Comment by jmezach** [comment]
@ErikEJ Just to clarify, are you talking about setting the build action to `Build`, or are you referring to doing a `dotnet build`? Because I wouldn't expect the build action being set to `Build` to work actually ;).

**Comment by ErikEJ** [comment]
Sorry, just mean running Build in VS works

**Comment by jmezach** [comment]
Okay, great. Thanks for the feedback. And if you run into any more issues don't hesitate to create a new one.

**Comment by ErikEJ** [comment]
You are welcome, this is a great project! I may have a look at: https://github.com/jmezach/MSBuild.Sdk.SqlProj/issues/6
