### ISSUE TITLE
Log verbosity

### ISSUE THREAD

**Issue by molszews** [jmezach/MSBuild.Sdk.SqlProj#7]
Hey, I did `sed` on sql files to get rid of sqlcmd variables, while the sqlproj project seems to work just fine csproj is reporting one problem which at the moment is impossible to trace due to the size of the project:
![image](https://user-images.githubusercontent.com/2878612/80146491-38182200-85b2-11ea-909e-33f98c3e220a.png)

Is there any way to increase log verbosity?

**Comment by molszews** [comment]
Seems like sqlproj way of building is automagically inserting GOs between files?

**Comment by jmezach** [comment]
@molszews That's interesting. You don't get this error when building the `.dacpac` using `.sqlproj`?

As for some log verbosity, have a look at the output from the Build. It should show you the files being added to the model and will probably give a clue about which file is causing this error.

**Comment by molszews** [comment]
I think this is related to PostDeployment scripts, I have many sql files that are not table models but migrations scripts, there is one marked as entry file in sqlproj:
`<PostDeploy Include="PostDeployment\runMigrations.sql" />`
which then uses sqlcmd syntax to include other files `:r .\disableTriggers.sql` btw. these are set in sqlproj as `<None Include="PostDeployment\disableTriggers.sql" />`

when I remove PostDeployment dir with all migration scripts then dacpac builds just fine

**Comment by jmezach** [comment]
Yes, by default we include all `.sql` files into the compilation, except for those in the folders `Post-Deployment` and `Pre-Deployment` (see the [ItemGroup here](https://github.com/jmezach/MSBuild.Sdk.SqlProj/blob/bcd1402178f117001b067a18e4d4862bedc5cb56/src/MSBuild.Sdk.SqlProj/Sdk/Sdk.props#L38-L44)). I believe those are the names of folders that you get when you create a new `.sqlproj` project.

You could try to rename the `PostDeployment` folder to `Post-Deployment`, or you can edit the `.csproj` and add this to it:

```xml
<ItemGroup>
  <Content Exclude="PostDeployment\**\*.sql" />
</ItemGroup>
```

That will probably fix building the `.dacpac`, but will probably not include the post deployment scripts you currently have. For that to work we'll probably need to add support for the `PostDeploy` and `PreDeploy` build actions somehow.

**Comment by ErikEJ** [comment]
I dont think those folders are created by default - just the Postdeploy/Predeploy Build action on the related scripts (and they can also refer to some scripts with build action None)

    This file contains SQL statements that will be appended to the build script.		
     Use SQLCMD syntax to include a file in the post-deployment script.			
     Example:      :r .\myfile.sql

**Comment by jmezach** [comment]
;) Maybe that's just how we've setup our projects. Perhaps we shouldn't exclude those by default anymore, although that would be a breaking change. Either way we'll probably want to add support for post deployment scripts. I'm just not sure how those can be added to the model and if they resolve those references by default or that we need to add some logic to make that happen. That does sound like a different feature than what is being requested here though, so maybe we should open a separate issue.

**Comment by ErikEJ** [comment]
Agree, proper support for pre and post is a separate issue.

**Comment by molszews** [comment]
ok, seems to me this issue can be closed now

**Comment by molszews** [comment]
btw @jmezach any hints re local setup to play with MSBuild.Sdk.Sqlproj locally? I mean, other way than publishing nuget package

**Comment by jmezach** [comment]
Have a look at the test projects. They mostly just include the Sdk.props and Sdk.targets files directly which should work if you want to try out changes locally.
